# Generated by Django 5.2 on 2025-04-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='asset_life_years',
            field=models.IntegerField(blank=True, help_text='Target years of operation', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='country_risk_score',
            field=models.FloatField(blank=True, help_text='Risk score based on home/target country', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='funding_leverage',
            field=models.FloatField(blank=True, help_text='Debt to equity ratio (impacts capex and cash flow)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='home_country',
            field=models.CharField(blank=True, help_text='Country of origin for investment', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='off_taker_rating',
            field=models.CharField(blank=True, help_text='Credit rating of energy buyer (impacts revenue)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='off_taker_risk_score',
            field=models.FloatField(blank=True, help_text='Risk score based on off-taker rating', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='overall_risk_score',
            field=models.FloatField(blank=True, help_text='Aggregate risk score for the project', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status_risk',
            field=models.CharField(blank=True, choices=[('early_stage', 'Early Stage (Higher Risk)'), ('development', 'Development'), ('construction', 'Construction'), ('operational', 'Operational (Lower Risk)')], help_text='Project development status risk level', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status_risk_score',
            field=models.FloatField(blank=True, help_text='Risk score based on project status', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_country',
            field=models.CharField(blank=True, help_text='Target country for the project', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_state_province',
            field=models.CharField(blank=True, help_text='State/province within target country', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technology_risk_factor',
            field=models.FloatField(blank=True, help_text='Energy yield variability factor (0-1)', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technology_risk_score',
            field=models.FloatField(blank=True, help_text='Risk score based on technology type', null=True),
        ),
    ]
